#!/usr/bin/env python

import daemon
import os
import sys

from keepasshttp import main

if '-d' in sys.argv:
    display = os.environ.get('DISPLAY')
    cwd = os.path.abspath('.')
    with daemon.DaemonContext():
        if display:
            os.environ['DISPLAY'] = display
        try:
            main.main(cwd)
        except:
            main.LOG.exception('Main failed')
else:
    main.main()
